server:
  port: 9001
loggin:
  level:
    org:
      springframework:
        security: TRACE
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000