openapi: 3.0.0
info:
  title: TPV Mesas API
  version: 1.0.0
paths:
  /mesas/buscar:
    get:
      summary: Obtener mesa por id
      description: Devuelve una mesa específica utilizando un parámetro de consulta.
      parameters:
        - name: id
          in: query
          required: true
          description: El ID de la mesa a obtener.
          schema:
            type: string
      responses:
        '200':
          description: Mesa solicitada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mesas'
        '400':
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Parámetro 'id' es requerido."
  /mesas:
    get:
      summary: Obtener todas las mesas
      responses:
        '200':
          description: Lista de mesas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mesas'
    put:
      summary: Actualiza los datos de una mesa.
      description: Actualiza los datos de una mesa específica en el sistema.
      operationId: updateMesa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mesas'
      responses:
        '200':
          description: La mesa se actualizó correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de éxito.
                    example: "Mesa actualizada correctamente."
        '400':
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Descripción del error.
                    example: "El campo 'nombreTradicional' es obligatorio."
        '401':
          description: No autorizado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Descripción del error.
                    example: "Token inválido o expirado."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Descripción del error.
                    example: "Ocurrió un error inesperado."  

  /mesas/{id}/nombre:
    patch:
      summary: Modificar nombre de la mesa
      description: Actualiza el nombre de la mesa.
      operationId: cambiaNombreMesa
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la mesa a renombrar.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Nuevo nombre"
      responses:
        '200':
          description: Nombre de la mesa actualizado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Nombre actualizado exitosamente."
        '400':
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    
  /mesas/{id}/camarero:
    patch:
      summary: Modificar camarero de la mesa
      description: Actualiza el camarero de la mesa.
      operationId: cambiaCamareroMesa
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la mesa a renombrar.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                camarero:
                  type: string
                  example: "Nuevo nombre"
      responses:
        '200':
          description: Camarero de la mesa actualizado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Nombre actualizado exitosamente."
        '400':
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string                    

  /mesas/{id}:
    delete:
      summary: Borrar mesa
      description: Elimina una mesa del sistema.
      operationId: borraMesa
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la mesa a eliminar.
          schema:
            type: string
      responses:
        '200':
          description: Mesa eliminada correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Mesa eliminada exitosamente."
        '400':
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /mesas/{id}/imprimir:
    post:
      summary: Imprimir mesa
      description: Inicia el proceso de impresión de la mesa.
      operationId: imprimeMesa
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la mesa a imprimir.
          schema:
            type: string
      responses:
        '200':
          description: Proceso de impresión iniciado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Impresión iniciada."
        '400':
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /mesas/cobrar:
    post:
      summary: Cobrar mesa
      description: Realiza el cobro de una mesa y finaliza la transacción.
      operationId: cobraMesa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ID de la mesa a cobrar.
                  example: "123e4567-e89b-12d3-a456-426614174000"
                tipoPago:
                  type: string
                  enum: [ CASH, TPV ]
                  description: Método de pago utilizado.
                  example: "TPV"
      responses:
        '200':
          description: La mesa fue cobrada correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Mesa cobrada exitosamente."
        '400':
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "ID de mesa inválido."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error inesperado al cobrar la mesa."
  /pedidos:
    get:
      summary: Obtener todos los pedidos existentes
      description: Devuelve una lista de todos los pedidos registrados en la base de datos.
      tags:
        - Pedidos
      responses:
        '200':
          description: Lista de pedidos obtenida con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pedido'
        '500':
          description: Error al obtener los pedidos                    

components:
  schemas:
    Mesas:
      type: object
      properties:
        id:
          type: string
          format: uuid
        mesaReferencia:
          type: string
          format: uuid
        numero:
          type: integer
        sector:
          type: string
        nombre:
          type: string
        ocupada:
          type: boolean
        camarero:
          type: string
        cantidad:
          type: number
          format: float
        estado:
          type: string
        lastUpdatedAt:
          type: string
          format: date-time
        version:
          type: integer
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductoEnMesa'
    ProductoEnMesa:
      type: object
      properties:
        id:
          type: string
          format: uuid
        mesaReferencia:
          type: string
        productoReferencia:
          type: string        
        unidades:
          type: integer
        precio:
          type: number
          format: float
        nombre:
          type: string
        code:
          type: string
        estado:
          type: string
        fechaHoraPedido:
          type: string
          format: date-time
        fechaHoraServido:
          type: string
          format: date-time
        fechaHoraCreacion:
          type: string
          format: date-time
        version:
          type: integer
    Pedido:
      type: object
      properties:
        sector:
          type: string
        numeroMesa:
          type: integer
        nombreMesa:
          type: string
        camarero:
          type: string
        product:
          $ref: '#/components/schemas/ProductoEnMesa'
